name: Maven Build

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:


jobs:
  maven-build:
    uses: telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    with:
      # No Docker based tests in this repository
      USES_DOCKERHUB_IMAGES: false
      # Want SNAPSHOTs to be published from main
      PUBLISH_SNAPSHOTS: true
      MAIN_BRANCH: main
      MAVEN_DEBUG_ARGS: -Dlogback.configurationFile=logback-debug.xml
      JAVA_VERSION: 21
      PUBLISH_JACOCO_REPORT: true
    secrets: inherit

  docker-build:
    needs: maven-build
    uses: telicent-oss/shared-workflows/.github/workflows/docker-push-to-registries.yml@main
    with:
      APP_NAME: rdf-abac-evaluator
      APP_NAME_PREFIX: ""
      PATH: .
      DOCKERFILE: ./Dockerfile
      VERSION: ${{ needs.maven-build.outputs.version }}
      TARGET: rdf-abac-evaluator
      BUILD_ARGS: |
        PROJECT_VERSION=${{ needs.maven-build.outputs.version }}
      USES_MAVEN: true
      # Container image is built for Java 21 to be as up to date as possible
      JAVA_VERSION: 21
      GRYPE_SECURITY_ISSUES_BLOCK_ONLY_IF_FIX_AVAILABLE: true
    secrets: inherit